from _token import _MQTT_SERVER, _GATEWAY_TOKEN, _NGROK_TOKEN, _SERVER_IPS

# commond
MQTT_SERVER = _MQTT_SERVER
GATEWAY_TOKEN = _GATEWAY_TOKEN
NGROK_TOKEN = _NGROK_TOKEN

# kaco
SERVER_IPS = _SERVER_IPS

# Config
TIME_WAIT_S = 60
TIME_WAIT_READ_ATTRIBUTE_S = 20
